In [1]:
import pandas as pd

In [2]:
df_stations = pd.read_csv('ev_stations_2025.csv')
df_stations.head()

,id,title,address,town,state,postcode,country,lat,lon,operator,status,num_connectors,connector_types,date_added
0,462769,Electra - Wambrechies - Volfoni,81 Av. Clément Ader,Wambrechies,NaN,59118,FR,50.685653,3.062410,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:58:00+00:00
1,462768,Electra - Tourcoing - Action,185 rue du Touquet,Tourcoing,NaN,59200,FR,50.723171,3.180636,Electra,Operational,3,CCS (Type 2)|CHAdeMO|Type 2 (Socket Only),2025-11-02 09:55:00+00:00
2,462767,Electra - Bondues - Sure Hotel by Best Western...,3 Av. Henri Becquerel,Bondues,NaN,59910,FR,50.722535,3.129496,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:50:00+00:00
3,462766,Electra - Bousbecque - Intermarché,Rue Auger,Bousbecque,NaN,59166,FR,50.770139,3.083454,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:46:00+00:00
4,462765,Electra - Halluin - Intermarché,Boulevard de Roncq,Halluin,NaN,59250,FR,50.769938,3.124030,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:42:00+00:00

In [3]:
df_stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10000 non-null  int64
 1   title            10000 non-null  object
 2   address          9999 non-null   object
 3   town             9797 non-null   object
 4   state            7131 non-null   object
 5   postcode         8330 non-null   object
 6   country          10000 non-null  object
 7   lat              10000 non-null  float64
 8   lon              10000 non-null  float64
 9   operator         9402 non-null   object
 10  status           10000 non-null  object
 11  num_connectors   10000 non-null  int64
 12  connector_types  9995 non-null   object
 13  date_added       10000 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 1.1+ MB

In [4]:
df_stations.isnull().sum()

id                    0
title                 0
address               1
town                203
state              2869
postcode           1670
country               0
lat                   0
lon                   0
operator            598
status                0
num_connectors        0
connector_types       5
date_added            0
dtype: int64

In [5]:
df_stat = df_stations.copy()
df_stat.head()

,id,title,address,town,state,postcode,country,lat,lon,operator,status,num_connectors,connector_types,date_added
0,462769,Electra - Wambrechies - Volfoni,81 Av. Clément Ader,Wambrechies,NaN,59118,FR,50.685653,3.062410,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:58:00+00:00
1,462768,Electra - Tourcoing - Action,185 rue du Touquet,Tourcoing,NaN,59200,FR,50.723171,3.180636,Electra,Operational,3,CCS (Type 2)|CHAdeMO|Type 2 (Socket Only),2025-11-02 09:55:00+00:00
2,462767,Electra - Bondues - Sure Hotel by Best Western...,3 Av. Henri Becquerel,Bondues,NaN,59910,FR,50.722535,3.129496,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:50:00+00:00
3,462766,Electra - Bousbecque - Intermarché,Rue Auger,Bousbecque,NaN,59166,FR,50.770139,3.083454,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:46:00+00:00
4,462765,Electra - Halluin - Intermarché,Boulevard de Roncq,Halluin,NaN,59250,FR,50.769938,3.124030,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:42:00+00:00

In [7]:
df_stat.duplicated().sum()

np.int64(0)

In [12]:
#Cleaning Whitespace if any
for col in df_stat.columns:
    if df_stat[col].dtype == 'object' or str(df_stat[col].dtype) == 'string':
        df_stat[col] = df_stat[col].str.strip().str.title()

In [13]:
df_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10000 non-null  int64
 1   title            10000 non-null  object
 2   address          9999 non-null   object
 3   town             9797 non-null   object
 4   state            7131 non-null   object
 5   postcode         8330 non-null   object
 6   country          10000 non-null  object
 7   lat              10000 non-null  float64
 8   lon              10000 non-null  float64
 9   operator         9402 non-null   object
 10  status           10000 non-null  object
 11  num_connectors   10000 non-null  int64
 12  connector_types  9995 non-null   object
 13  date_added       10000 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 1.1+ MB

In [15]:
# validating latitude and longitude
df_stat = df_stat[(df_stat['lat'].between(-90,90)) & (df_stat['lon'].between(-180,180))]

In [16]:
df_stat.shape

(10000, 14)

In [17]:
#dtype
df_stat['date_added'] = pd.to_datetime(df_stat['date_added'])

In [18]:
df_stat['date_added'].head()

0   2025-11-02 09:58:00+00:00
1   2025-11-02 09:55:00+00:00
2   2025-11-02 09:50:00+00:00
3   2025-11-02 09:46:00+00:00
4   2025-11-02 09:42:00+00:00
Name: date_added, dtype: datetime64[ns, UTC]

In [19]:
df_stat['connector_types'].unique()

array(['Ccs (Type 2)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Chademo|Type 2 (Socket Only)',
       'Type 2 (Socket Only)', 'Ccs (Type 2)',
       'Type 2 (Socket Only)|Cee 7/4 - Schuko - Type F',
       'Ccs (Type 2)|Ccs (Type 2)', 'Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Chademo|Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Type 2 (Socket Only)|Chademo',
       'Chademo|Ccs (Type 2)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Chademo|Type 2 (Tethered Connector) |Type 2 (Socket Only)',
       'Ccs (Type 2)|Type 2 (Socket Only)|Ccs (Type 2)', 'Unknown',
       'Ccs (Type 2)|Unknown', 'Ccs (Type 1)', nan,
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Ccs (Type 2)|Type 2 (Tethered Connector) |Ccs (Type 2)',
       'Ccs (Type 2)|Type 1 (J1772)', 'Ccs (Type 1)|Chademo',
       'Ccs (Type 2)|Chademo',
       'Ccs (Type 2)|Type 2 (Socket Only)|Cee 7/4 - Schuko - Type F',
       'Type 2 (Socket Only)|Scame Type 3A (Low Power)',
       'Ccs (Type 2)|Ccs (Type 2)|Chademo|Type 2 (Socket Only)',
       'Ccs (Type 2)|Iec 60309 3-Pin',
       'Ccs (Type 1)|Gb-T Dc - Gb/T 20234.3',
       'Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Tesla (Model S/X)|Ccs (Type 1)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Chademo',
       'Cee 7/4 - Schuko - Type F',
       'Ccs (Type 1)|Nacs / Tesla Supercharger',
       'Ccs (Type 1)|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 1)|Ccs (Type 2)',
       'Chademo|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Ccs (Type 2)|Type 2 (Socket Only)',
       'Chademo|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Ccs (Type 1)|Ccs (Type 2)|Tesla (Model S/X)',
       'Type 1 (J1772)|Ccs (Type 2)',
       'Chademo|Type 2 (Socket Only)|Ccs (Type 2)',
       'Nacs / Tesla Supercharger', 'Type 2 (Socket Only)|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Ccs (Type 2)',
       'Ccs (Type 2)|Ccs (Type 2)|Chademo',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Chademo',
       'Type 2 (Socket Only)|Chademo|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Chademo|Ccs (Type 2)', 'Cee 7/5',
       'Chademo|Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Chademo|Ccs (Type 2)',
       'Bs1363 3 Pin 13 Amp', 'Ccs (Type 2)|Nacs / Tesla Supercharger',
       'Type 1 (J1772)', 'Cee 7/4 - Schuko - Type F|Cee 5 Pin',
       'Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Nema 6-15',
       'Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Cee 7/5|Type 1 (J1772)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Cee 7/4 - Schuko - Type F|Cee 7/4 - Schuko - Type F',
       'Cee 7/4 - Schuko - Type F|Type 2 (Socket Only)',
       'Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Chademo|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Chademo',
       'Ccs (Type 2)|Type 2 (Socket Only)|Unknown',
       'Ccs (Type 1)|Ccs (Type 1)',
       'Ccs (Type 1)|Ccs (Type 1)|Ccs (Type 1)',
       'Type 1 (J1772)|Type 1 (J1772)', 'Cee 3 Pin',
       'Cee 7/4 - Schuko - Type F|Type 2 (Socket Only)|Type 2 (Tethered Connector)',
       'Type 2 (Socket Only)|Ccs (Type 2)|Chademo',
       'Type 2 (Socket Only)|Type 2 (Tethered Connector) |Ccs (Type 2)|Chademo',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Unknown|Gb-T Dc - Gb/T 20234.3',
       'Type 1 (J1772)|Ccs (Type 1)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Ccs (Type 1)|Ccs (Type 1)|Nacs / Tesla Supercharger|Nacs / Tesla Supercharger',
       'Ccs (Type 1)|Type 1 (J1772)', 'Unknown|Unknown',
       'Ccs (Type 1)|Nacs / Tesla Supercharger|Type 1 (J1772)',
       'Nacs / Tesla Supercharger|Type 1 (J1772)',
       'Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector) |Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Ccs (Type 1)|Nacs / Tesla Supercharger|Chademo',
       'Ccs (Type 1)|Chademo|Ccs (Type 1)|Ccs (Type 1)|Nacs / Tesla Supercharger',
       'Gb-T Ac - Gb/T 20234.2 (Socket)|Type 2 (Socket Only)',
       'Type 2 (Socket Only)|Gb-T Ac - Gb/T 20234.2 (Socket)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Type 2 (Tethered Connector)',
       'Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Type 2 (Socket Only)',
       'Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Chademo', 'Unknown|Ccs (Type 1)', 'Type 2 (Socket Only)|Unknown',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Type 2 (Socket Only)',
       'Cee 7/4 - Schuko - Type F|Cee 3 Pin|Cee 5 Pin',
       'Type 2 (Tethered Connector) |Type 1 (J1772)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Chademo',
       'Chademo|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Chademo|Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Chademo|Type 2 (Tethered Connector) |Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Ccs (Type 2)|Type 2 (Socket Only)|Chademo',
       'Ccs (Type 1)|Type 1 (J1772)|Chademo',
       'Ccs (Type 2)|Type 2 (Socket Only)|Gb-T Dc - Gb/T 20234.3',
       'Nacs / Tesla Supercharger|Nacs / Tesla Supercharger',
       'Type 2 (Socket Only)|Ccs (Type 2)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Type 1 (J1772)|Nacs / Tesla Supercharger',
       'Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)', 'Tesla (Model S/X)',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Ccs (Type 2)',
       'Ccs (Type 1)|Unknown', 'Unknown|Unknown|Unknown',
       'Type 2 (Socket Only)|Gb-T Ac - Gb/T 20234.2 (Tethered Cable)',
       'Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)',
       'Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)',
       'Chademo|Ccs (Type 1)|Type 2 (Tethered Connector) |Chademo|Ccs (Type 2)|Type 1 (J1772)|Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)',
       'Ccs (Type 2)|Ccs (Type 2)|Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 1 (J1772)|Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Chademo|Ccs (Type 2)',
       'Ccs (Type 1)|Chademo|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Ccs (Type 2)|Chademo',
       'Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Chademo',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)',
       'Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Chademo|Ccs (Type 2)',
       'Chademo|Chademo|Chademo|Chademo',
       'Ccs (Type 2)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Ccs (Type 2)|Type 2 (Socket Only)|Type 2 (Socket Only)|Ccs (Type 2)',
       'Ccs (Type 2)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 1)|Type 1 (J1772)',
       'Type 1 (J1772)|Chademo|Ccs (Type 1)', 'Chademo|Ccs (Type 1)',
       'Chademo|Ccs (Type 1)|Ccs (Type 1)', 'Type 1 (J1772)|Chademo',
       'Nema 5-15R|Type 1 (J1772)',
       'Tesla (Model S/X)|Chademo|Ccs (Type 1)|Nacs / Tesla Supercharger',
       'Nema 5-20R',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)|Type 2 (Socket Only)',
       'Chademo|Type 2 (Socket Only)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Ccs (Type 2)',
       'Chademo|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Ccs (Type 2)|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Chademo|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Chademo|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Gb-T Dc - Gb/T 20234.3|Chademo|Ccs (Type 2)|Type 2 (Tethered Connector)',
       'Chademo|Ccs (Type 2)|Chademo|Ccs (Type 2)',
       'Type 2 (Socket Only)|Type 2 (Socket Only)|Type 1 (J1772)',
       'Chademo|Ccs (Type 2)|Type 2 (Socket Only)|Chademo|Ccs (Type 2)',
       'Ccs (Type 2)|Chademo|Type 2 (Socket Only)|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3',
       'Chademo|Ccs (Type 2)|Type 2 (Socket Only)|Gb-T Ac - Gb/T 20234.2 (Socket)|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Type 2 (Socket Only)',
       'Gb-T Dc - Gb/T 20234.3|Chademo|Ccs (Type 2)|Type 2 (Socket Only)',
       'Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Ccs (Type 2)',
       'Type 1 (J1772)|Type 2 (Socket Only)',
       'Gb-T Dc - Gb/T 20234.3|Chademo|Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3',
       'Gb-T Ac - Gb/T 20234.2 (Socket)',
       'Ccs (Type 2)|Gb-T Dc - Gb/T 20234.3|Gb-T Dc - Gb/T 20234.3|Type 2 (Socket Only)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)|Ccs (Type 2)',
       'Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)|Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Ccs (Type 2)|Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Ccs (Type 2)',
       'Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)',
       'Chademo|Ccs (Type 2)|Chademo',
       'Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)',
       'Tesla (Model S/X)|Ccs (Type 1)|Tesla (Model S/X)|Ccs (Type 1)|Tesla (Model S/X)|Ccs (Type 1)',
       'Chademo|Ccs (Type 1)|Nacs / Tesla Supercharger',
       'Tesla (Model S/X)|Ccs (Type 1)|Nacs / Tesla Supercharger',
       'Tesla (Model S/X)|Nacs / Tesla Supercharger',
       'Nacs / Tesla Supercharger|Ccs (Type 1)'], dtype=object)

In [20]:
df_stat['connector_count'] = df_stat['connector_types'].str.count(',') + 1

In [21]:
df_stat.head()

,id,title,address,town,state,postcode,country,lat,lon,operator,status,num_connectors,connector_types,date_added,connector_count
0,462769,Electra - Wambrechies - Volfoni,81 Av. Clément Ader,Wambrechies,NaN,59118,Fr,50.685653,3.062410,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:58:00+00:00,1.0
1,462768,Electra - Tourcoing - Action,185 Rue Du Touquet,Tourcoing,NaN,59200,Fr,50.723171,3.180636,Electra,Operational,3,Ccs (Type 2)|Chademo|Type 2 (Socket Only),2025-11-02 09:55:00+00:00,1.0
2,462767,Electra - Bondues - Sure Hotel By Best Western...,3 Av. Henri Becquerel,Bondues,NaN,59910,Fr,50.722535,3.129496,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:50:00+00:00,1.0
3,462766,Electra - Bousbecque - Intermarché,Rue Auger,Bousbecque,NaN,59166,Fr,50.770139,3.083454,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:46:00+00:00,1.0
4,462765,Electra - Halluin - Intermarché,Boulevard De Roncq,Halluin,NaN,59250,Fr,50.769938,3.124030,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:42:00+00:00,1.0

In [28]:
df_stat['connector_count'].unique().shape

(2,)

In [29]:
df_stat.drop('connector_count',axis=1, inplace=True)

In [30]:
df_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10000 non-null  int64
 1   title            10000 non-null  object
 2   address          9999 non-null   object
 3   town             9797 non-null   object
 4   state            7131 non-null   object
 5   postcode         8330 non-null   object
 6   country          10000 non-null  object
 7   lat              10000 non-null  float64
 8   lon              10000 non-null  float64
 9   operator         9402 non-null   object
 10  status           10000 non-null  object
 11  num_connectors   10000 non-null  int64
 12  connector_types  9995 non-null   object
 13  date_added       10000 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(2), int64(2), object(9)
memory usage: 1.1+ MB

In [31]:
null_df = df_stat[df_stat[['town','state','postcode','country']].isna().any(axis=1)]
null_df.head()

,id,title,address,town,state,postcode,country,lat,lon,operator,status,num_connectors,connector_types,date_added
0,462769,Electra - Wambrechies - Volfoni,81 Av. Clément Ader,Wambrechies,NaN,59118,Fr,50.685653,3.062410,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:58:00+00:00
1,462768,Electra - Tourcoing - Action,185 Rue Du Touquet,Tourcoing,NaN,59200,Fr,50.723171,3.180636,Electra,Operational,3,Ccs (Type 2)|Chademo|Type 2 (Socket Only),2025-11-02 09:55:00+00:00
2,462767,Electra - Bondues - Sure Hotel By Best Western...,3 Av. Henri Becquerel,Bondues,NaN,59910,Fr,50.722535,3.129496,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:50:00+00:00
3,462766,Electra - Bousbecque - Intermarché,Rue Auger,Bousbecque,NaN,59166,Fr,50.770139,3.083454,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:46:00+00:00
4,462765,Electra - Halluin - Intermarché,Boulevard De Roncq,Halluin,NaN,59250,Fr,50.769938,3.124030,Electra,Operational,2,Ccs (Type 2)|Type 2 (Socket Only),2025-11-02 09:42:00+00:00

In [32]:
null_df.shape

(3222, 14)

In [33]:
countries_null = (
    df_stat[df_stat[['town','state','postcode']].isna().any(axis=1)]['country']
    .dropna().unique()
)
countries_null

array(['Fr', 'Es', 'It', 'Fi', 'Tr', 'Br', 'Be', 'Tn', 'Us', 'At', 'Nl',
       'Az', 'Pl', 'Hu', 'In', 'Ie', 'Lv', 'Au', 'Ch', 'Li', 'Mx', 'Gb',
       'De', 'Jo', 'Si', 'Pa', 'Dk', 'Il', 'Ro', 'Za', 'Eg', 'Cz', 'Cn',
       'Ae', 'Do', 'Vn', 'My', 'Ge', 'Mt', 'Gt', 'Ec', 'Jm', 'Ru', 'Cr',
       'Lk', 'Co', 'Pt', 'Id', 'Hr', 'Lu', 'Nz', 'Se', 'Ma', 'Bg', 'Gr',
       'Jp', 'Lt', 'Ca', 'Cy', 'Uy', 'Ua', 'Np', 'Md', 'Al', 'Py', 'No'],
      dtype=object)

In [36]:
missing_by_country = (
    df_stat[df_stat[['town','state','postcode']].isna().any(axis=1)]
    .groupby('country').size().sort_values(ascending=False)
)
missing_by_country

country
Es    875
Ru    384
My    366
Tr    362
Dk    296
     ...
Pa      1
Py      1
Pt      1
Uy      1
Za      1
Length: 66, dtype: int64

In [37]:
# Countries having greater than 10 null values
countries_gt10 = missing_by_country[missing_by_country > 10]
countries_gt10

country
Es    875
Ru    384
My    366
Tr    362
Dk    296
Br    110
Fr    107
Nl     92
It     86
Ie     78
Cz     59
De     58
At     38
Gb     29
Ge     27
Eg     25
Lt     21
Jp     16
Be     15
Au     14
Ch     11
dtype: int64

In [39]:
countries_gt10.shape

(21,)

In [41]:
df_stat['country'].value_counts().loc['Nl']

np.int64(95)

In [42]:
country_code_with_name = {
    'Es':'Spain', 'Ru':'Russia', 'My':'Malaysia', 'Tr':'Turkey',
    'Dk':'Denmark', 'Br':'Brazil', 'Fr':'France', 'Nl':'Netherlands',
    'It':'Italy', 'Cz':'Czech Republic', 'De':'Germany', 'At':'Austria',
    'Gb':'United Kingdom', 'Ge':'Georgia', 'Eg':'Egypt', 'Lt':'Lithuania',
    'Jp':'Japan', 'Be':'Belgium', 'Au':'Australia','Ch':'Switzerland',
    'Ie':'Treland'
}

In [43]:
# to check if usable coordinates are there
df_to_fill = df_stat[
    (df_stat['country'].isin(['Es','Ru','My','Tr','Dk','Br','Fr','Nl','It','Cz','De','At','Gb','Ge','Eg','Lt','Jp','Be','Au','Ch','Ie'])) &
    (df_stat[['town','state','postcode']].isna().any(axis=1))
]

In [44]:
df_to_fill[['lat','lon']].isna().sum()

lat    0
lon    0
dtype: int64

In [45]:
# Filling one country at a time
es_df = df_stat[
    (df_stat['country'] == 'Es') &
    (df_stat[['town','state','postcode']].isna().any(axis=1))
]
es_df.head()

,id,title,address,town,state,postcode,country,lat,lon,operator,status,num_connectors,connector_types,date_added
5,462763,Ayunt. El Palau D'Anglesola,El Palau D'Anglesola,El Palau D'Anglesola,NaN,NaN,Es,41.648502,0.876808,Etecnic,Operational,1,Type 2 (Socket Only),2025-11-02 07:14:00+00:00
6,462762,Energia Nufri,Mollerusa,Mollerusa,NaN,NaN,Es,41.640457,0.886628,Etecnic,Operational,1,Ccs (Type 2),2025-11-02 07:08:00+00:00
7,462761,Hotel Jardí,Mollerusa,Mollerusa,NaN,NaN,Es,41.631459,0.896505,(Business Owner At Location),Operational,1,Type 2 (Socket Only),2025-11-02 07:05:00+00:00
8,462760,Ayunt. Miralcamp,Miralcamp,Miralcamp,NaN,NaN,Es,41.606143,0.881104,Etecnic,Operational,1,Type 2 (Socket Only),2025-11-02 07:01:00+00:00
9,462759,Ayunt. Arbeca,Arbeca,Arbeca,NaN,NaN,Es,41.542113,0.924948,Etecnic,Operational,1,Type 2 (Socket Only),2025-11-02 06:59:00+00:00

In [46]:
len(es_df)

875

In [47]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(user_agent='ev_station_cleaning')
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=1)

In [50]:
for idx,row in es_df.iterrows():
  location = reverse((row['lat'],row['lon']), language='en')

  if location:
    addr = location.raw.get('address',{})

    if pd.isna(df_stat.at[idx,'town']):
      df_stat.at[idx,'town'] = (
          addr.get('town') or addr.get('city') or addr.get('village'))
    if pd.isna(df_stat.at[idx,'postcode']):
      df_stat.at[idx,'postcode'] = addr.get('postcode')
    if pd.isna(df_stat.at[idx,'state']):
      df_stat.at[idx,'state'] = addr.get('state')

In [51]:
df_stat.loc[
    df_stat['country'] == 'Es',
    ['town','state','postcode']
].isna().sum()

town         1
state        5
postcode    19
dtype: int64

In [52]:
# After cleaning from 875 we got only 25 left which is success rate of about 97%

In [54]:
countries = list(country_code_with_name)
countries

['Es',
 'Ru',
 'My',
 'Tr',
 'Dk',
 'Br',
 'Fr',
 'Nl',
 'It',
 'Cz',
 'De',
 'At',
 'Gb',
 'Ge',
 'Eg',
 'Lt',
 'Jp',
 'Be',
 'Au',
 'Ch',
 'Ie']

In [56]:
countries.remove('Es')

In [57]:
countries

['Ru',
 'My',
 'Tr',
 'Dk',
 'Br',
 'Fr',
 'Nl',
 'It',
 'Cz',
 'De',
 'At',
 'Gb',
 'Ge',
 'Eg',
 'Lt',
 'Jp',
 'Be',
 'Au',
 'Ch',
 'Ie']

In [62]:
for cont in countries:
  cont_df = df_stat[
    (df_stat['country'] == cont) &
    (df_stat[['town','state','postcode']].isna().any(axis=1))]
  for idx,row in cont_df.iterrows():
    location = reverse((row['lat'],row['lon']), language='en')

    if location:
      addr = location.raw.get('address',{})

      if pd.isna(df_stat.at[idx,'town']):
        df_stat.at[idx,'town'] = (
            addr.get('town') or addr.get('city') or addr.get('village') or addr.get('municipality'))
      if pd.isna(df_stat.at[idx,'postcode']):
        df_stat.at[idx,'postcode'] = addr.get('postcode')
      if pd.isna(df_stat.at[idx,'state']):
        df_stat.at[idx,'state'] = addr.get('state')

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=44.99874&lon=41.11973&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=39.81951&lon=32.56424&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=55.90944063&lon=12.31209328&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=55.81807592&lon=12.48796703&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=36.79615592005929&lon=138.2171071071023&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=51.09884786536605&lon=2.5815829513380777&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=53.34084027398157&lon=-6.284232228026326&format=json&accept-language=en&addressdetails=1

In [63]:
df_stat.isnull().sum()

id                   0
title                0
address              1
town                15
state              564
postcode           251
country              0
lat                  0
lon                  0
operator           598
status               0
num_connectors       0
connector_types      5
date_added           0
dtype: int64

In [67]:
remain_countries = df_stat[df_stat[['town','state','postcode']].isna().any(axis=1)]['country'].dropna().unique()
remain_countries

array(['Fi', 'Tr', 'Br', 'Tn', 'Us', 'Az', 'Pl', 'It', 'Hu', 'In', 'Ie',
       'Lv', 'Li', 'Mx', 'Jo', 'Si', 'Pa', 'Es', 'Il', 'Ro', 'Za', 'Cn',
       'Ae', 'Do', 'Eg', 'Vn', 'Ge', 'Cz', 'Mt', 'Gt', 'Ec', 'Jm', 'My',
       'Cr', 'Lk', 'Co', 'Pt', 'Id', 'Hr', 'Lu', 'Nz', 'Se', 'Ma', 'Bg',
       'Gr', 'Jp', 'Ca', 'Cy', 'Uy', 'At', 'Ua', 'Np', 'Md', 'Al', 'Py',
       'No'], dtype=object)

In [68]:
for cont in remain_countries:
  cont_df = df_stat[
    (df_stat['country'] == cont) &
    (df_stat[['town','state','postcode']].isna().any(axis=1))]
  for idx,row in cont_df.iterrows():
    location = reverse((row['lat'],row['lon']), language='en')

    if location:
      addr = location.raw.get('address',{})

      if pd.isna(df_stat.at[idx,'town']):
        df_stat.at[idx,'town'] = (
            addr.get('town') or addr.get('city') or addr.get('village') or addr.get('municipality'))
      if pd.isna(df_stat.at[idx,'postcode']):
        df_stat.at[idx,'postcode'] = addr.get('postcode')
      if pd.isna(df_stat.at[idx,'state']):
        df_stat.at[idx,'state'] = addr.get('state')

In [69]:
df_stat.isnull().sum()

id                   0
title                0
address              1
town                 1
state              522
postcode           161
country              0
lat                  0
lon                  0
operator           598
status               0
num_connectors       0
connector_types      5
date_added           0
dtype: int64

In [70]:
for idx,row in df_stat[df_stat['state'].isna()].iterrows():
  location = reverse((row['lat'],row['lon']), language='en')

  if location:
    addr = location.raw.get('address',{})

    if pd.isna(df_stat.at[idx,'state']):
      df_stat.at[idx,'state'] = addr.get('state') or addr.get('region') or addr.get('province') or addr.get('state_district') or addr.get('county')

In [71]:
df_stat.isnull().sum()

id                   0
title                0
address              1
town                 1
state              128
postcode           161
country              0
lat                  0
lon                  0
operator           598
status               0
num_connectors       0
connector_types      5
date_added           0
dtype: int64

In [73]:
rows_miss = df_stat[df_stat[['town','state','postcode']].isna().any(axis=1)]
rows_miss.shape

(288, 14)

In [74]:
# 288 null we will drop
df_stat.dropna(subset=['town','state','postcode'], inplace=True)

In [75]:
df_stat['operator'] = df_stat['operator'].fillna('Unknown')
df_stat['connector_types'] = df_stat['connector_types'].fillna('Unknown')

In [76]:
df_stat.isnull().sum()

id                 0
title              0
address            1
town               0
state              0
postcode           0
country            0
lat                0
lon                0
operator           0
status             0
num_connectors     0
connector_types    0
date_added         0
dtype: int64

In [78]:
df_stat.dropna(inplace=True)

In [79]:
df_stat.isnull().sum()

id                 0
title              0
address            0
town               0
state              0
postcode           0
country            0
lat                0
lon                0
operator           0
status             0
num_connectors     0
connector_types    0
date_added         0
dtype: int64

In [80]:
# Null Values Handled

In [81]:
df_stat['year_added'] = df_stat['date_added'].dt.year
df_stat['month_added'] = df_stat['date_added'].dt.month
df_stat['day_added'] = df_stat['date_added'].dt.day

In [84]:
df_stat['quarter'] = df_stat['date_added'].dt.quarter

In [85]:
df_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9711 entries, 0 to 9710
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               9711 non-null   int64
 1   title            9711 non-null   object
 2   address          9711 non-null   object
 3   town             9711 non-null   object
 4   state            9711 non-null   object
 5   postcode         9711 non-null   object
 6   country          9711 non-null   object
 7   lat              9711 non-null   float64
 8   lon              9711 non-null   float64
 9   operator         9711 non-null   object
 10  status           9711 non-null   object
 11  num_connectors   9711 non-null   int64
 12  connector_types  9711 non-null   object
 13  date_added       9711 non-null   datetime64[ns, UTC]
 14  year_added       9711 non-null   int32
 15  month_added      9711 non-null   int32
 16  day_added        9711 non-null   int32
 17  quarter          9711 non-null   int32
dtypes: datetime64[ns, UTC](1), float64(2), int32(4), int64(2), object(9)
memory usage: 1.2+ MB

In [86]:
df_stat.reset_index(drop=True, inplace=True)

In [87]:
df_stat.describe()

,id,lat,lon,num_connectors,year_added,month_added,day_added,quarter
count,9711.000000,9711.000000,9711.000000,9711.000000,9711.0,9711.000000,9711.000000,9711.000000
mean,415263.324065,42.917701,-55.314506,1.438163,2025.0,6.686232,18.953146,2.337452
std,39986.977863,14.091149,62.009045,0.971086,0.0,1.284100,5.504587,0.598244
min,374562.000000,-43.904364,-159.356940,0.000000,2025.0,6.000000,1.000000,2.000000
25%,378621.500000,42.341217,-113.535919,1.000000,2025.0,6.000000,20.000000,2.000000
50%,384045.000000,45.850965,-73.527149,1.000000,2025.0,6.000000,20.000000,2.000000
75%,459431.500000,48.697955,-1.628777,2.000000,2025.0,7.000000,21.000000,3.000000
max,462769.000000,68.377358,174.756158,26.000000,2025.0,11.000000,31.000000,4.000000

In [88]:
df_stat['status'].value_counts(dropna=False)

status
Operational                   9031
Planned For Future Date        289
Temporarily Unavailable        176
Not Operational                130
Unknown                         80
Partly Operational (Mixed)       5
Name: count, dtype: int64

In [90]:
df_stat['operator'].value_counts()

operator
Circuit Electrique    1979
Chargepoint           1275
Flo                    724
Unknown                598
Powergo                420
                      ...
Chargenet Nz             1
Mer                      1
Flash Charging           1
Turnongreen              1
Hwisel Ev                1
Name: count, Length: 253, dtype: int64

In [91]:
df_stat['connector_types'].value_counts()

connector_types
Type 1 (J1772)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      4416
Type 2 (Socket Only)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 759
Chademo|Ccs (Type 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 714
Ccs (Type 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         650
Ccs (Type 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         490
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...
Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)|Chademo|Ccs (Type 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Tesla (Model S/X)|Ccs (Type 1)|Tesla (Model S/X)|Ccs (Type 1)|Tesla (Model S/X)|Ccs (Type 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Ccs (Type 2)|Chademo|Ccs (Type 2)|Ccs (Type 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector) |Type 2 (Tethered Connector)       1
Tesla (Model S/X)|Nacs / Tesla Supercharger                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Name: count, Length: 193, dtype: int64

In [92]:
df_stat.to_csv('cleaned_ev_stations_2025.csv', index=False)