In [51]:
import pandas as pd

In [52]:
df_traffic = pd.read_csv('FAF4.5.1_HiLoForecasts.csv')
df_traffic.head().T

                      0         1         2         3         4
fr_orig             NaN       NaN       NaN       NaN       NaN
dms_orig        11.0000   11.0000   11.0000   11.0000   11.0000
dms_dest        11.0000   19.0000  129.0000  131.0000  139.0000
fr_dest             NaN       NaN       NaN       NaN       NaN
fr_inmode           NaN       NaN       NaN       NaN       NaN
dms_mode         1.0000    1.0000    1.0000    1.0000    1.0000
fr_outmode          NaN       NaN       NaN       NaN       NaN
sctg2            1.0000    1.0000    1.0000    1.0000    1.0000
trade_type       1.0000    1.0000    1.0000    1.0000    1.0000
tons_2012       17.3922  220.0650    1.0854    6.1655    2.7483
tons_2020       23.2025  237.5213    0.8036    5.4115    2.1696
tons_2020_opt   23.6688  241.9686    0.8223    5.5404    2.2190
tons_2020_pes   22.2720  228.4169    0.7680    5.1588    2.0719
tons_2025       25.7482  247.8935    0.7851    5.4685    2.0737
tons_2025_opt   26.7281  256.6083    0.8188    5.7089    2.1608
tons_2025_pes   24.4284  235.8412    0.7432    5.1616    1.9606
tons_2030       28.2930  257.0915    0.7695    5.6906    2.0484
tons_2030_opt   30.0025  271.4294    0.8202    6.0834    2.1833
tons_2030_pes   26.2145  238.9120    0.7135    5.2559    1.8940
tons_2035       31.4560  268.2908    0.7485    5.8616    2.0056
tons_2035_opt   33.9683  288.0485    0.8112    6.3851    2.1769
tons_2035_pes   28.4731  243.4636    0.6804    5.3003    1.8145
tons_2040       34.6558  282.2260    0.7759    5.8447    1.9171
tons_2040_opt   38.2776  309.6131    0.8573    6.5079    2.1264
tons_2040_pes   30.5821  249.7306    0.6885    5.1552    1.6916
tons_2045       35.7685  293.4628    0.8419    6.3670    2.0444
tons_2045_opt   39.5064  321.9390    0.9302    7.0894    2.2677
tons_2045_pes   31.5637  259.6719    0.7470    5.6158    1.8040
value_2012      32.9385  269.8723    1.5510    9.6137    4.1406
value_2020      43.9425  291.2794    1.1483    8.4380    3.2688
value_2020_opt  44.8255  296.7333    1.1751    8.6391    3.3432
value_2020_pes  42.1802  280.1145    1.0974    8.0440    3.1215
value_2025      48.7637  303.9993    1.1219    8.5268    3.1243
value_2025_opt  50.6195  314.6865    1.1701    8.9017    3.2554
value_2025_pes  46.2640  289.2191    1.0619    8.0483    2.9538
value_2030      53.5832  315.2790    1.0996    8.8731    3.0861
value_2030_opt  56.8208  332.8621    1.1720    9.4856    3.2893
value_2030_pes  49.6467  292.9850    1.0195    8.1953    2.8536
value_2035      59.5734  329.0130    1.0695    9.1398    3.0216
value_2035_opt  64.3314  353.2425    1.1592    9.9562    3.2797
value_2035_pes  53.9243  298.5667    0.9722    8.2646    2.7337
value_2040      65.6334  346.1022    1.1088    9.1135    2.8883
value_2040_opt  72.4927  379.6878    1.2251   10.1476    3.2037
value_2040_pes  57.9183  306.2522    0.9839    8.0383    2.5486
value_2045      67.7407  359.8823    1.2030    9.9279    3.0801
value_2045_opt  74.8199  394.8034    1.3292   11.0544    3.4165
value_2045_pes  59.7775  318.4435    1.0675    8.7566    2.7179
tmiles_2012      0.3237   25.3876    0.6798    1.5839    0.8705
tmiles_2020      0.4318   27.4014    0.5033    1.3902    0.6872
tmiles_2025      0.4791   28.5980    0.4917    1.4049    0.6569
tmiles_2030      0.5265   29.6591    0.4819    1.4619    0.6488
tmiles_2035      0.5854   30.9511    0.4688    1.5058    0.6353
tmiles_2040      0.6449   32.5587    0.4860    1.5015    0.6072
tmiles_2045      0.6656   33.8550    0.5272    1.6357    0.6476
wgt_dist        18.6118  115.3641  626.3129  256.8973  316.7413

In [53]:
df_traffic.describe().T

,count,mean,std,min,25%,50%,75%,max
fr_orig,580464.0,804.677815,2.335670,801.0000,803.000000,804.000000,807.000000,808.0000
dms_orig,1580516.0,297.750840,157.321048,11.0000,160.000000,319.000000,441.000000,560.0000
dms_dest,1580516.0,297.370897,158.381283,11.0000,139.000000,321.000000,451.000000,560.0000
fr_dest,569813.0,804.291450,2.363008,801.0000,802.000000,804.000000,806.000000,808.0000
fr_inmode,580464.0,3.393477,1.104441,1.0000,3.000000,3.000000,4.000000,7.0000
dms_mode,1580516.0,3.036950,1.690399,1.0000,1.000000,4.000000,4.000000,8.0000
fr_outmode,569813.0,3.330770,1.121259,1.0000,3.000000,3.000000,4.000000,7.0000
sctg2,1580516.0,28.405168,10.619842,1.0000,23.000000,31.000000,36.000000,99.0000
trade_type,1580516.0,2.088309,0.790531,1.0000,1.000000,2.000000,3.000000,3.0000
tons_2012,1580516.0,10.725918,320.119898,0.0000,0.000200,0.007000,0.140600,83136.0000
tons_2020,1580516.0,12.471864,370.407910,0.0000,0.000100,0.007100,0.163600,93083.4688
tons_2020_opt,1580516.0,12.813603,379.374309,0.0000,0.000100,0.007500,0.169100,95377.1953
tons_2020_pes,1580516.0,11.960124,355.855782,0.0000,0.000100,0.006600,0.155200,89070.0000
tons_2025,1580516.0,13.195556,389.455417,0.0000,0.000200,0.008600,0.184383,94695.7969
tons_2025_opt,1580516.0,13.788804,405.129905,0.0000,0.000200,0.009400,0.194900,98618.9063
tons_2025_pes,1580516.0,12.502033,370.675200,0.0000,0.000112,0.007700,0.171200,90229.1641
tons_2030,1580516.0,13.829700,404.272427,0.0000,0.000200,0.010200,0.205200,91319.8906
tons_2030_opt,1580516.0,14.747755,428.835930,0.0000,0.000200,0.011500,0.221700,96785.1875
tons_2030_pes,1580516.0,12.841152,377.856891,0.0000,0.000200,0.008800,0.185900,86037.7266
tons_2035,1580516.0,14.491578,419.790718,0.0000,0.000200,0.012200,0.230200,92912.6016
tons_2035_opt,1580516.0,15.744579,453.365170,0.0000,0.000300,0.014087,0.254000,99205.0781
tons_2035_pes,1580516.0,13.190979,385.500778,0.0000,0.000200,0.010200,0.203100,86272.8438
tons_2040,1580516.0,15.274653,436.309570,0.0000,0.000300,0.015100,0.262700,102592.6484
tons_2040_opt,1580516.0,16.999008,482.418301,0.0000,0.000300,0.017900,0.297800,111251.7109
tons_2040_pes,1580516.0,13.606575,393.196357,0.0000,0.000200,0.012100,0.225200,91840.7109
tons_2045,1580516.0,16.116339,453.867565,0.0000,0.000300,0.017508,0.293100,109119.0234
tons_2045_opt,1580516.0,18.066167,504.389047,0.0000,0.000400,0.021400,0.337100,118336.3672
tons_2045_pes,1580516.0,14.277400,408.436089,-0.0002,0.000200,0.013300,0.245700,97685.9844
value_2012,1580516.0,11.217356,193.962031,0.0000,0.004400,0.069500,0.957200,63788.0000
value_2020,1580516.0,13.663680,230.350545,0.0000,0.003600,0.080500,1.171000,66338.5360
value_2020_opt,1580516.0,14.126446,238.218773,0.0000,0.003800,0.085100,1.218700,67992.4960
value_2020_pes,1580516.0,12.996645,219.380023,0.0000,0.003300,0.074700,1.105100,63470.7040
value_2025,1580516.0,15.141504,249.100293,0.0000,0.004400,0.096900,1.352325,66309.6120
value_2025_opt,1580516.0,16.009347,263.587353,0.0000,0.004800,0.105500,1.444200,69056.7200
value_2025_pes,1580516.0,14.122392,233.087554,0.0000,0.003800,0.086500,1.240000,63181.9040
value_2030,1580516.0,16.709290,270.359443,0.0000,0.005200,0.113500,1.536400,72000.1520
value_2030_opt,1580516.0,18.111834,294.133226,0.0000,0.005800,0.126400,1.679900,82186.0160
value_2030_pes,1580516.0,15.184671,246.638161,0.0000,0.004400,0.098600,1.373100,66916.6000
value_2035,1580516.0,18.564717,299.109812,0.0000,0.006200,0.133400,1.754800,88311.7440
value_2035_opt,1580516.0,20.635467,335.930367,0.0000,0.007200,0.152200,1.967700,105830.3600
value_2035_pes,1580516.0,16.388547,265.220139,0.0000,0.005100,0.112100,1.520100,77886.6080
value_2040,1580516.0,21.075621,341.734208,0.0000,0.007700,0.161300,2.052100,109762.0240
value_2040_opt,1580516.0,24.249306,402.871499,0.0000,0.009200,0.189300,2.365700,138052.6240
value_2040_pes,1580516.0,17.985365,292.497309,0.0000,0.006100,0.130800,1.719000,98085.9120
value_2045,1580516.0,23.450864,383.676409,0.0000,0.009000,0.184400,2.311400,133760.3600
value_2045_opt,1580516.0,27.616841,470.616454,0.0000,0.011100,0.222000,2.717100,174826.7040
value_2045_pes,1580516.0,19.534473,319.170203,-0.0370,0.006700,0.142600,1.877100,120500.3120
tmiles_2012,1580516.0,3.086858,115.014568,0.0000,0.000200,0.005300,0.126800,55585.6143
tmiles_2020,1580516.0,3.516831,108.760480,0.0000,0.000100,0.005300,0.147000,48572.4230
tmiles_2025,1580516.0,3.767280,112.859081,0.0000,0.000100,0.006500,0.165700,52559.3258
tmiles_2030,1580516.0,3.988854,114.727272,0.0000,0.000100,0.007700,0.184100,51110.0076
tmiles_2035,1580516.0,4.232862,117.455947,0.0000,0.000199,0.009142,0.206500,48329.3467
tmiles_2040,1580516.0,4.538463,120.397299,0.0000,0.000200,0.011300,0.235800,44806.5849
tmiles_2045,1580516.0,4.851313,123.319926,0.0000,0.000200,0.013000,0.263000,40249.5379
wgt_dist,1580516.0,1072.081912,876.957941,0.0000,394.542825,868.185450,1500.000000,9970.0000

In [54]:
df_traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1580516 entries, 0 to 1580515
Data columns (total 55 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   fr_orig         580464 non-null   float64
 1   dms_orig        1580516 non-null  int64
 2   dms_dest        1580516 non-null  int64
 3   fr_dest         569813 non-null   float64
 4   fr_inmode       580464 non-null   float64
 5   dms_mode        1580516 non-null  int64
 6   fr_outmode      569813 non-null   float64
 7   sctg2           1580516 non-null  int64
 8   trade_type      1580516 non-null  int64
 9   tons_2012       1580516 non-null  float64
 10  tons_2020       1580516 non-null  float64
 11  tons_2020_opt   1580516 non-null  float64
 12  tons_2020_pes   1580516 non-null  float64
 13  tons_2025       1580516 non-null  float64
 14  tons_2025_opt   1580516 non-null  float64
 15  tons_2025_pes   1580516 non-null  float64
 16  tons_2030       1580516 non-null  float64
 17  tons_2030_opt   1580516 non-null  float64
 18  tons_2030_pes   1580516 non-null  float64
 19  tons_2035       1580516 non-null  float64
 20  tons_2035_opt   1580516 non-null  float64
 21  tons_2035_pes   1580516 non-null  float64
 22  tons_2040       1580516 non-null  float64
 23  tons_2040_opt   1580516 non-null  float64
 24  tons_2040_pes   1580516 non-null  float64
 25  tons_2045       1580516 non-null  float64
 26  tons_2045_opt   1580516 non-null  float64
 27  tons_2045_pes   1580516 non-null  float64
 28  value_2012      1580516 non-null  float64
 29  value_2020      1580516 non-null  float64
 30  value_2020_opt  1580516 non-null  float64
 31  value_2020_pes  1580516 non-null  float64
 32  value_2025      1580516 non-null  float64
 33  value_2025_opt  1580516 non-null  float64
 34  value_2025_pes  1580516 non-null  float64
 35  value_2030      1580516 non-null  float64
 36  value_2030_opt  1580516 non-null  float64
 37  value_2030_pes  1580516 non-null  float64
 38  value_2035      1580516 non-null  float64
 39  value_2035_opt  1580516 non-null  float64
 40  value_2035_pes  1580516 non-null  float64
 41  value_2040      1580516 non-null  float64
 42  value_2040_opt  1580516 non-null  float64
 43  value_2040_pes  1580516 non-null  float64
 44  value_2045      1580516 non-null  float64
 45  value_2045_opt  1580516 non-null  float64
 46  value_2045_pes  1580516 non-null  float64
 47  tmiles_2012     1580516 non-null  float64
 48  tmiles_2020     1580516 non-null  float64
 49  tmiles_2025     1580516 non-null  float64
 50  tmiles_2030     1580516 non-null  float64
 51  tmiles_2035     1580516 non-null  float64
 52  tmiles_2040     1580516 non-null  float64
 53  tmiles_2045     1580516 non-null  float64
 54  wgt_dist        1580516 non-null  float64
dtypes: float64(50), int64(5)
memory usage: 663.2 MB

In [55]:
df_traffic.shape

(1580516, 55)

In [56]:
cop_df = df_traffic.copy()

In [57]:
cop_df[['fr_orig','fr_dest','fr_inmode','fr_outmode']].nunique()

fr_orig       8
fr_dest       8
fr_inmode     7
fr_outmode    7
dtype: int64

In [58]:
cop_df[['fr_orig','fr_dest','fr_inmode','fr_outmode']].value_counts(dropna=False)

fr_orig  fr_dest  fr_inmode  fr_outmode
NaN      NaN      NaN        NaN           430239
807.0    NaN      3.0        NaN            68641
804.0    NaN      3.0        NaN            62709
                  4.0        NaN            53776
807.0    NaN      4.0        NaN            45751
                                            ...
806.0    NaN      5.0        NaN              101
NaN      801.0    NaN        6.0               99
         802.0    NaN        6.0               52
805.0    NaN      5.0        NaN               24
802.0    NaN      6.0        NaN               21
Name: count, Length: 71, dtype: int64

In [59]:
cop_df['fr_dest'].value_counts(dropna=False)

fr_dest
NaN      1010703
801.0     103673
804.0      86145
803.0      72833
806.0      69946
807.0      67808
808.0      66776
802.0      54376
805.0      48256
Name: count, dtype: int64

In [60]:
cop_df['fr_orig'].value_counts(dropna=False)

fr_orig
NaN      1000052
804.0     121398
807.0     118755
801.0      85952
808.0      67976
806.0      65150
803.0      53448
802.0      40501
805.0      27284
Name: count, dtype: int64

In [61]:
cop_df['fr_inmode'].value_counts(dropna=False)

fr_inmode
NaN    1000052
3.0     263677
4.0     208001
1.0      48044
5.0      32299
7.0      15887
2.0      12332
6.0        224
Name: count, dtype: int64

In [62]:
cop_df.duplicated().sum()

np.int64(0)

In [63]:
(cop_df.isnull().sum()/len(cop_df)) *100

fr_orig           63.273766
dms_orig           0.000000
dms_dest           0.000000
fr_dest           63.947660
fr_inmode         63.273766
dms_mode           0.000000
fr_outmode        63.947660
sctg2              0.000000
trade_type         0.000000
tons_2012          0.000000
tons_2020          0.000000
tons_2020_opt      0.000000
tons_2020_pes      0.000000
tons_2025          0.000000
tons_2025_opt      0.000000
tons_2025_pes      0.000000
tons_2030          0.000000
tons_2030_opt      0.000000
tons_2030_pes      0.000000
tons_2035          0.000000
tons_2035_opt      0.000000
tons_2035_pes      0.000000
tons_2040          0.000000
tons_2040_opt      0.000000
tons_2040_pes      0.000000
tons_2045          0.000000
tons_2045_opt      0.000000
tons_2045_pes      0.000000
value_2012         0.000000
value_2020         0.000000
value_2020_opt     0.000000
value_2020_pes     0.000000
value_2025         0.000000
value_2025_opt     0.000000
value_2025_pes     0.000000
value_2030         0.000000
value_2030_opt     0.000000
value_2030_pes     0.000000
value_2035         0.000000
value_2035_opt     0.000000
value_2035_pes     0.000000
value_2040         0.000000
value_2040_opt     0.000000
value_2040_pes     0.000000
value_2045         0.000000
value_2045_opt     0.000000
value_2045_pes     0.000000
tmiles_2012        0.000000
tmiles_2020        0.000000
tmiles_2025        0.000000
tmiles_2030        0.000000
tmiles_2035        0.000000
tmiles_2040        0.000000
tmiles_2045        0.000000
wgt_dist           0.000000
dtype: float64

In [64]:
# Negative values
(cop_df.select_dtypes(include='number') < 0).sum()

fr_orig            0
dms_orig           0
dms_dest           0
fr_dest            0
fr_inmode          0
dms_mode           0
fr_outmode         0
sctg2              0
trade_type         0
tons_2012          0
tons_2020          0
tons_2020_opt      0
tons_2020_pes      0
tons_2025          0
tons_2025_opt      0
tons_2025_pes      0
tons_2030          0
tons_2030_opt      0
tons_2030_pes      0
tons_2035          0
tons_2035_opt      0
tons_2035_pes      0
tons_2040          0
tons_2040_opt      0
tons_2040_pes      0
tons_2045          0
tons_2045_opt      0
tons_2045_pes      2
value_2012         0
value_2020         0
value_2020_opt     0
value_2020_pes     0
value_2025         0
value_2025_opt     0
value_2025_pes     0
value_2030         0
value_2030_opt     0
value_2030_pes     0
value_2035         0
value_2035_opt     0
value_2035_pes     0
value_2040         0
value_2040_opt     0
value_2040_pes     0
value_2045         0
value_2045_opt     0
value_2045_pes    24
tmiles_2012        0
tmiles_2020        0
tmiles_2025        0
tmiles_2030        0
tmiles_2035        0
tmiles_2040        0
tmiles_2045        0
wgt_dist           0
dtype: int64

In [65]:
cop_df.loc[cop_df['tons_2045_pes'] < 0 , 'tons_2045_pes'] = 0
cop_df.loc[cop_df['value_2045_pes'] < 0 , 'value_2045_pes'] = 0

In [66]:
# Negative values
(cop_df.select_dtypes(include='number') < 0).sum().sum()

np.int64(0)

<h1> Feature Engineering</h1>

In [67]:
cop_df['tons_growth'] = cop_df['tons_2045_pes'] - cop_df['tons_2012']
cop_df['value_growth'] = cop_df['value_2045_pes'] - cop_df['value_2012']
cop_df['tmiles_growth'] = cop_df['tmiles_2045'] - cop_df['tmiles_2012']

In [68]:
cop_df.head().T

                      0         1         2         3         4
fr_orig             NaN       NaN       NaN       NaN       NaN
dms_orig        11.0000   11.0000   11.0000   11.0000   11.0000
dms_dest        11.0000   19.0000  129.0000  131.0000  139.0000
fr_dest             NaN       NaN       NaN       NaN       NaN
fr_inmode           NaN       NaN       NaN       NaN       NaN
dms_mode         1.0000    1.0000    1.0000    1.0000    1.0000
fr_outmode          NaN       NaN       NaN       NaN       NaN
sctg2            1.0000    1.0000    1.0000    1.0000    1.0000
trade_type       1.0000    1.0000    1.0000    1.0000    1.0000
tons_2012       17.3922  220.0650    1.0854    6.1655    2.7483
tons_2020       23.2025  237.5213    0.8036    5.4115    2.1696
tons_2020_opt   23.6688  241.9686    0.8223    5.5404    2.2190
tons_2020_pes   22.2720  228.4169    0.7680    5.1588    2.0719
tons_2025       25.7482  247.8935    0.7851    5.4685    2.0737
tons_2025_opt   26.7281  256.6083    0.8188    5.7089    2.1608
tons_2025_pes   24.4284  235.8412    0.7432    5.1616    1.9606
tons_2030       28.2930  257.0915    0.7695    5.6906    2.0484
tons_2030_opt   30.0025  271.4294    0.8202    6.0834    2.1833
tons_2030_pes   26.2145  238.9120    0.7135    5.2559    1.8940
tons_2035       31.4560  268.2908    0.7485    5.8616    2.0056
tons_2035_opt   33.9683  288.0485    0.8112    6.3851    2.1769
tons_2035_pes   28.4731  243.4636    0.6804    5.3003    1.8145
tons_2040       34.6558  282.2260    0.7759    5.8447    1.9171
tons_2040_opt   38.2776  309.6131    0.8573    6.5079    2.1264
tons_2040_pes   30.5821  249.7306    0.6885    5.1552    1.6916
tons_2045       35.7685  293.4628    0.8419    6.3670    2.0444
tons_2045_opt   39.5064  321.9390    0.9302    7.0894    2.2677
tons_2045_pes   31.5637  259.6719    0.7470    5.6158    1.8040
value_2012      32.9385  269.8723    1.5510    9.6137    4.1406
value_2020      43.9425  291.2794    1.1483    8.4380    3.2688
value_2020_opt  44.8255  296.7333    1.1751    8.6391    3.3432
value_2020_pes  42.1802  280.1145    1.0974    8.0440    3.1215
value_2025      48.7637  303.9993    1.1219    8.5268    3.1243
value_2025_opt  50.6195  314.6865    1.1701    8.9017    3.2554
value_2025_pes  46.2640  289.2191    1.0619    8.0483    2.9538
value_2030      53.5832  315.2790    1.0996    8.8731    3.0861
value_2030_opt  56.8208  332.8621    1.1720    9.4856    3.2893
value_2030_pes  49.6467  292.9850    1.0195    8.1953    2.8536
value_2035      59.5734  329.0130    1.0695    9.1398    3.0216
value_2035_opt  64.3314  353.2425    1.1592    9.9562    3.2797
value_2035_pes  53.9243  298.5667    0.9722    8.2646    2.7337
value_2040      65.6334  346.1022    1.1088    9.1135    2.8883
value_2040_opt  72.4927  379.6878    1.2251   10.1476    3.2037
value_2040_pes  57.9183  306.2522    0.9839    8.0383    2.5486
value_2045      67.7407  359.8823    1.2030    9.9279    3.0801
value_2045_opt  74.8199  394.8034    1.3292   11.0544    3.4165
value_2045_pes  59.7775  318.4435    1.0675    8.7566    2.7179
tmiles_2012      0.3237   25.3876    0.6798    1.5839    0.8705
tmiles_2020      0.4318   27.4014    0.5033    1.3902    0.6872
tmiles_2025      0.4791   28.5980    0.4917    1.4049    0.6569
tmiles_2030      0.5265   29.6591    0.4819    1.4619    0.6488
tmiles_2035      0.5854   30.9511    0.4688    1.5058    0.6353
tmiles_2040      0.6449   32.5587    0.4860    1.5015    0.6072
tmiles_2045      0.6656   33.8550    0.5272    1.6357    0.6476
wgt_dist        18.6118  115.3641  626.3129  256.8973  316.7413
tons_growth     14.1715   39.6069   -0.3384   -0.5497   -0.9443
value_growth    26.8390   48.5712   -0.4835   -0.8571   -1.4227
tmiles_growth    0.3419    8.4674   -0.1526    0.0518   -0.2229

In [69]:
import numpy as np

In [70]:
cop_df['tons_growth_perc'] = (
    cop_df['tons_growth'] / cop_df['tons_2012'].replace(0, np.nan)
) * 100
cop_df['value_growth_perc'] = (
    cop_df['value_growth'] / cop_df['value_2012'].replace(0, np.nan)
) * 100
cop_df['tmiles_growth_perc'] = (
    cop_df['tmiles_growth'] / cop_df['tmiles_2012'].replace(0, np.nan)
) * 100

In [71]:
cop_df.head().T

                             0          1           2           3           4
fr_orig                    NaN        NaN         NaN         NaN         NaN
dms_orig             11.000000  11.000000   11.000000   11.000000   11.000000
dms_dest             11.000000  19.000000  129.000000  131.000000  139.000000
fr_dest                    NaN        NaN         NaN         NaN         NaN
fr_inmode                  NaN        NaN         NaN         NaN         NaN
...                        ...        ...         ...         ...         ...
value_growth         26.839000  48.571200   -0.483500   -0.857100   -1.422700
tmiles_growth         0.341900   8.467400   -0.152600    0.051800   -0.222900
tons_growth_perc     81.481929  17.997819  -31.177446   -8.915741  -34.359422
value_growth_perc    81.482156  17.997846  -31.173436   -8.915402  -34.359755
tmiles_growth_perc  105.622490  33.352503  -22.447779    3.270408  -25.605974

[61 rows x 5 columns]

In [72]:
np.isinf(cop_df['tons_growth_perc']).sum()

np.int64(0)

In [73]:
cop_df['sctg2'].value_counts()

sctg2
35    108820
34    100770
24     86387
33     83159
40     81678
30     79544
38     78435
36     76667
39     63834
23     63192
31     55383
32     54451
20     53061
43     52454
29     51804
37     51160
7      41891
26     40190
21     38265
28     35115
27     31793
3      29700
41     28413
4      23138
5      20911
6      20072
19     16959
22     16840
8      14897
13     14071
2      10357
1       8701
18      7950
25      7571
9       5613
17      5525
14      4815
11      4580
12      4043
10      3237
16      2826
15      2236
99         8
Name: count, dtype: int64

In [74]:
cop_df['trade_type'].value_counts()

trade_type
2    580464
3    569813
1    430239
Name: count, dtype: int64

In [75]:
cop_df['dms_mode'].value_counts(dropna=False)

dms_mode
1    513341
4    445902
5    337192
2    164307
3     86621
7     29474
6      3594
8        85
Name: count, dtype: int64

In [76]:
mode_map = {
    1: 'Truck' , 2: 'Rail' , 3: 'Water' , 4:'Air',
    5: 'Multiple_Modes_andRail' , 6: 'Pipeline' , 7: 'Unknown/Other' , 8: 'No_Domestic_Mode', np.nan:'Unknown/Other'
}
cop_df['dms_mode'] = cop_df['dms_mode'].map(mode_map)

In [77]:
commodity_map = {
    1:'Animal&Fish', 2:'Cereal_Grains', 3:'Agriculture_Products' ,4:'Animal_Origin_Products', 5:'Meat_Poultry_Seafood',
    6:'MilleGrain_Bakery', 7:'Fats&Oils', 8:'Alcoholic_beverages', 9:'Tobacco', 10:'Building_Stone',
    11:'Natural_Sands', 12:'Gravel_Crushed_Stone', 13:'Non-Metallic_Minerals', 14:'Metallic_ores', 15:'Coal',
    16:'Crude_Petroleum', 17:'Gasoline', 18:'Fuel_Oils', 19:'Other_CalPetrol_Products', 20:'Basic_Chemicals',
    21:'Pharmaceutical', 22:'Fertilizers', 23:'OtherChemical_Products', 24:'Plastic&Rubber', 25:'Logs&OtherWoods',
    26:'Wood_Products', 27:'Pulp_Paperboard_Newsprint_Paper', 28:'PaperorPaperboard_Articles', 29:'Printe_Products', 30:'Textiles_Leather_withArticles',
    31:'Non-Metallic_Minerals', 32:'BaseMetal_in_PrimaryorSemi-Finishedor Finished_Form', 33:'Articlesof_BaseMetal',
    34:'Machinery', 35:'Electronic',
    36:'Motorized&OtherVehicles', 37:'Transportation_Equipment', 38:'Precision_Instruments', 39:'Furniture_Mattresses',
    40:'Miscellaneous_Manufactured_Products',
    41:'Waste&Scrap', 43:'Mixed_Freight', 99:'Commodity_Unknown'
}
cop_df['sctg2'] = cop_df['sctg2'].map(commodity_map)

In [78]:
cop_df['sctg2'].head()

0    Animal&Fish
1    Animal&Fish
2    Animal&Fish
3    Animal&Fish
4    Animal&Fish
Name: sctg2, dtype: object

In [79]:
fr_map = {
    801:'Canada' , 802:'Mexico' , 803:'Rest_of_Americas' , 804:'Europe' ,
    805:'Africa' , 806:'Sw & Central Asia' , 807:'Eastern Asia' , 808:'SE Asia & Ocenia',
    np.nan:'Unknown'
}
cop_df['fr_orig'] = cop_df['fr_orig'].map(fr_map)
cop_df['fr_dest'] = cop_df['fr_dest'].map(fr_map)

In [80]:
cop_df['fr_dest'].value_counts()

fr_dest
Unknown              1010703
Canada                103673
Europe                 86145
Rest_of_Americas       72833
Sw & Central Asia      69946
Eastern Asia           67808
SE Asia & Ocenia       66776
Mexico                 54376
Africa                 48256
Name: count, dtype: int64

In [81]:
cop_df['fr_inmode'] = cop_df['fr_inmode'].map(mode_map)
cop_df['fr_outmode'] = cop_df['fr_outmode'].map(mode_map)

In [82]:
trade_map = {
    1:'Domestic', 2:'Import', 3:'Export'
}
cop_df['trade_type'] = cop_df['trade_type'].map(trade_map)

In [83]:
cop_df['dms_dest'].value_counts()

dms_dest
363    45959
61     42343
341    38454
486    35548
261    31115
       ...
499     4254
339     3771
560     3376
109     3102
159     2396
Name: count, Length: 132, dtype: int64

In [84]:
domestic_map = {
    11: "Birmingham-Hoover-Talladega, AL",
    12: "Mobile-Daphne-Fairhope, AL",
    19: "Remainder of Alabama",
    20: "Alaska",
    41: "Phoenix-Mesa-Glendale, AZ",
    42: "Tucson-Nogales, AZ",
    49: "Remainder of Arizona",
    50: "Remainder of Arkansas",
    61: "Los Angeles-Long Beach, CA",
    62: "Sacramento-Roseville, CA",
    63: "San Diego-Carlsbad-San Marcos, CA",
    64: "San Jose-San Francisco-Oakland, CA",
    65: "Fresno-Madera, CA",
    69: "Remainder of California",
    81: "Denver-Aurora, CO",
    89: "Remainder of Colorado",
    91: "Hartford-West Hartford-East Hartford, CT",
    92: "New York-Newark (CT Part)",
    99: "Remainder of Connecticut",
    101: "Philadelphia-Reading-Camden (DE Part)",
    109: "Remainder of Delaware",
    111: "Washington-Arlington-Alexandria (DC Part)",
    121: "Jacksonville-St. Marys-Palatka (FL Part)",
    122: "Miami-Fort Lauderdale-Port St. Lucie",
    123: "Orlando-Deltona-Daytona Beach",
    124: "Tampa-St. Petersburg-Clearwater",
    129: "Remainder of Florida",
    131: "Atlanta-Athens-Clarke County-Sandy Springs",
    132: "Savannah-Hinesville-Statesboro",
    139: "Remainder of Georgia",
    151: "Urban Honolulu",
    159: "Remainder of Hawaii",
    160: "Idaho",
    171: "Chicago-Naperville (IL Part)",
    172: "St. Louis (IL Part)",
    179: "Remainder of Illinois",
    181: "Chicago-Naperville (IN Part)",
    182: "Indianapolis-Carmel-Muncie",
    183: "Fort Wayne-Huntington-Auburn",
    189: "Remainder of Indiana",
    190: "Iowa",
    201: "Kansas City (KS Part)",
    202: "Wichita-Arkansas City-Winfield",
    209: "Remainder of Kansas",
    211: "Cincinnati (KY Part)",
    212: "Louisville/Jefferson County (KY Part)",
    219: "Remainder of Kentucky",
    221: "Baton Rouge",
    222: "Lake Charles",
    223: "New Orleans-Metairie-Hammond (LA Part)",
    229: "Remainder of Louisiana",
    230: "Maine",
    241: "Baltimore-Columbia-Towson",
    242: "Washington-Arlington-Alexandria (MD Part)",
    249: "Remainder of Maryland",
    251: "Boston-Worcester-Providence (MA Part)",
    259: "Remainder of Massachusetts",
    261: "Detroit-Warren-Ann Arbor",
    262: "Grand Rapids-Wyoming-Muskegon",
    269: "Remainder of Michigan",
    271: "Minneapolis-St. Paul (MN Part)",
    279: "Remainder of Minnesota",
    280: "Mississippi",
    291: "Kansas City (MO Part)",
    292: "St. Louis (MO Part)",
    299: "Remainder of Missouri",
    300: "Montana",
    311: "Omaha-Council Bluffs (NE Part)",
    319: "Remainder of Nebraska",
    321: "Las Vegas-Henderson (NV Part)",
    329: "Remainder of Nevada",
    331: "Boston-Worcester-Providence (NH Part)",
    339: "Remainder of New Hampshire",
    341: "New York-Newark (NJ Part)",
    342: "Philadelphia-Reading-Camden (NJ Part)",
    350: "New Mexico",
    361: "Albany-Schenectady",
    362: "Buffalo-Cheektowaga",
    363: "New York-Newark (NY Part)",
    364: "Rochester-Batavia-Seneca Falls",
    369: "Remainder of New York",
    371: "Charlotte-Concord (NC Part)",
    372: "Greensboro-Winston-Salem-High Point",
    373: "Raleigh-Durham-Chapel Hill",
    379: "Remainder of North Carolina",
    380: "North Dakota",
    391: "Cincinnati (OH Part)",
    392: "Cleveland-Akron-Canton",
    393: "Columbus-Marion-Zanesville",
    394: "Dayton-Springfield-Sidney",
    399: "Remainder of Ohio",
    401: "Oklahoma City-Shawnee",
    402: "Tulsa-Muskogee-Bartlesville",
    409: "Remainder of Oklahoma",
    411: "Portland-Vancouver-Salem (OR Part)",
    419: "Remainder of Oregon",
    421: "Philadelphia-Reading-Camden (PA Part)",
    422: "Pittsburgh-New Castle-Weirton",
    423: "New York-Newark (PA Part)",
    429: "Remainder of Pennsylvania",
    441: "Boston-Worcester-Providence (RI Part)",
    451: "Charleston-North Charleston-Summerville",
    452: "Greenville-Spartanburg-Anderson",
    459: "Remainder of South Carolina",
    460: "South Dakota",
    471: "Memphis (TN Part)",
    472: "Nashville-Davidson-Murfreesboro",
    473: "Knoxville-Morristown-Sevierville",
    479: "Remainder of Tennessee",
    481: "Austin-Round Rock",
    482: "Beaumont-Port Arthur",
    483: "Corpus Christi-Kingsville-Alice",
    484: "Dallas-Fort Worth (TX Part)",
    485: "El Paso-Las Cruces (TX Part)",
    486: "Houston-The Woodlands",
    487: "Laredo",
    488: "San Antonio-New Braunfels",
    489: "Remainder of Texas",
    491: "Salt Lake City-Provo-Orem",
    499: "Remainder of Utah",
    500: "Vermont",
    511: "Richmond",
    512: "Virginia Beach-Norfolk (VA Part)",
    513: "Washington-Arlington-Alexandria (VA Part)",
    519: "Remainder of Virginia",
    531: "Seattle-Tacoma",
    532: "Portland-Vancouver-Salem (WA Part)",
    539: "Remainder of Washington",
    540: "West Virginia",
    551: "Milwaukee-Racine-Waukesha",
    559: "Remainder of Wisconsin",
    560: "Wyoming"
}

In [85]:
cop_df['dms_dest'] = cop_df['dms_dest'].map(domestic_map)
cop_df['dms_orig'] = cop_df['dms_orig'].map(domestic_map)

In [86]:
cop_df['dms_dest'].head()

0               Birmingham-Hoover-Talladega, AL
1                          Remainder of Alabama
2                          Remainder of Florida
3    Atlanta-Athens-Clarke County-Sandy Springs
4                          Remainder of Georgia
Name: dms_dest, dtype: object

In [87]:
cop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1580516 entries, 0 to 1580515
Data columns (total 61 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   fr_orig             1580516 non-null  object
 1   dms_orig            1580516 non-null  object
 2   dms_dest            1580516 non-null  object
 3   fr_dest             1580516 non-null  object
 4   fr_inmode           1580516 non-null  object
 5   dms_mode            1580516 non-null  object
 6   fr_outmode          1580516 non-null  object
 7   sctg2               1580516 non-null  object
 8   trade_type          1580516 non-null  object
 9   tons_2012           1580516 non-null  float64
 10  tons_2020           1580516 non-null  float64
 11  tons_2020_opt       1580516 non-null  float64
 12  tons_2020_pes       1580516 non-null  float64
 13  tons_2025           1580516 non-null  float64
 14  tons_2025_opt       1580516 non-null  float64
 15  tons_2025_pes       1580516 non-null  float64
 16  tons_2030           1580516 non-null  float64
 17  tons_2030_opt       1580516 non-null  float64
 18  tons_2030_pes       1580516 non-null  float64
 19  tons_2035           1580516 non-null  float64
 20  tons_2035_opt       1580516 non-null  float64
 21  tons_2035_pes       1580516 non-null  float64
 22  tons_2040           1580516 non-null  float64
 23  tons_2040_opt       1580516 non-null  float64
 24  tons_2040_pes       1580516 non-null  float64
 25  tons_2045           1580516 non-null  float64
 26  tons_2045_opt       1580516 non-null  float64
 27  tons_2045_pes       1580516 non-null  float64
 28  value_2012          1580516 non-null  float64
 29  value_2020          1580516 non-null  float64
 30  value_2020_opt      1580516 non-null  float64
 31  value_2020_pes      1580516 non-null  float64
 32  value_2025          1580516 non-null  float64
 33  value_2025_opt      1580516 non-null  float64
 34  value_2025_pes      1580516 non-null  float64
 35  value_2030          1580516 non-null  float64
 36  value_2030_opt      1580516 non-null  float64
 37  value_2030_pes      1580516 non-null  float64
 38  value_2035          1580516 non-null  float64
 39  value_2035_opt      1580516 non-null  float64
 40  value_2035_pes      1580516 non-null  float64
 41  value_2040          1580516 non-null  float64
 42  value_2040_opt      1580516 non-null  float64
 43  value_2040_pes      1580516 non-null  float64
 44  value_2045          1580516 non-null  float64
 45  value_2045_opt      1580516 non-null  float64
 46  value_2045_pes      1580516 non-null  float64
 47  tmiles_2012         1580516 non-null  float64
 48  tmiles_2020         1580516 non-null  float64
 49  tmiles_2025         1580516 non-null  float64
 50  tmiles_2030         1580516 non-null  float64
 51  tmiles_2035         1580516 non-null  float64
 52  tmiles_2040         1580516 non-null  float64
 53  tmiles_2045         1580516 non-null  float64
 54  wgt_dist            1580516 non-null  float64
 55  tons_growth         1580516 non-null  float64
 56  value_growth        1580516 non-null  float64
 57  tmiles_growth       1580516 non-null  float64
 58  tons_growth_perc    1397397 non-null  float64
 59  value_growth_perc   1575183 non-null  float64
 60  tmiles_growth_perc  1397305 non-null  float64
dtypes: float64(52), object(9)
memory usage: 735.6+ MB

In [88]:
(cop_df['tons_2012'] == 0).sum()

np.int64(183119)

In [89]:
cop_df['tons_growth_perc'].isna().sum()

np.int64(183119)

In [90]:
(cop_df['tmiles_2012'] == 0).sum()

np.int64(183211)

In [91]:
cop_df['tmiles_growth_perc'].isna().sum()

np.int64(183211)

In [92]:
cop_df.to_csv('traffic_clean.csv', index=False)